name: Deploy via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configura chave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/github_deploy_key
          chmod 600 ~/.ssh/github_deploy_key
          ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy na VM via SSH
        run: |
          ssh -i ~/.ssh/github_deploy_key ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
            cd SeedApi
            git pull origin main
            docker compose down
            docker compose up -d --build
          EOF
